# To help show everything available to run and use in this repo
# More info: https://dcsil-team-app.herokuapp.com/docs/software/code/service_yml

tools:
  exceptions: https://sentry.io/organizations/dreamtune/issues/
  logging: 
    frontend: https://app.logdna.com/069caceba9/logs/view
    backend: https://console.firebase.google.com/u/0/project/dreamtune-cdf8a/functions/logs
  ci: https://github.com/dcsil/dream-team/actions
  firebase_console: https://console.firebase.google.com/u/0/project/dreamtune-cdf8a/overview

services:
  production: https://dreamtune-cdf8a.web.app/

docs:
  getting_started: https://github.com/dcsil/dream-team/blob/master/app/README.md

commands:
  bootstrap: ./bootstrap.sh
  database: https://console.firebase.google.com/u/0/project/dreamtune-cdf8a/database
  server: npm start
  test: npm run test-once
