# To help show everything available to run and use in this repo

tools:
  exceptions: https://sentry.io/organizations/dreamtune/issues/
  logging: https://app.logdna.com/069caceba9/logs/view
  ci: https://github.com/dcsil/dream-team/actions?query=workflow%3ACI
  
services:
  production: https://dashboard.heroku.com/apps/dreamtune
  staging: https://dashboard.heroku.com/apps/dreamtune-stage

docs:
  getting_started: ./README.md
  app_specific: ./django-web-app/README.md

commands:
  bootstrap: script/bootstrap
  database: https://console.firebase.google.com/u/0/project/dreamtune-cdf8a/database
  server: cd app/django-web-app; python3 manage.py runserver
  test: echo "test command here" 
