# To help show everything available to run and use in this repo
# More info: https://dcsil-team-app.herokuapp.com/docs/software/code/service_yml

tools:
  exceptions: https://sentry.io/organizations/dreamtune/issues/
  logging: https://app.logdna.com/069caceba9/logs/view
  ci: https://github.com/dcsil/dream-team/actions?query=workflow%3AReactAppCI
  firebase_console: https://console.firebase.google.com/u/0/project/dreamtune-cdf8a/overview
  
services:
  production: https://dreamtune-cdf8a.web.app/

docs:
  getting_started: ./README.md

commands:
  bootstrap: ./bootstrap/bootstrap.sh
  database: https://console.firebase.google.com/u/0/project/dreamtune-cdf8a/database
  server: npm start
  test: npm test 
