tools:
  exceptions: https://sentry.io/organizations/dreamtune/issues/
  logging: https://app.logdna.com/069caceba9/logs/view
  ci:
    frontend: ../.github/workflows/index_tests.yml
    backend: ../.github/workflows/backend.yml
  # front end CI will contain several workflows for different pages.
  # collection of testing scripts can be found in /django-web-app/tests
  
services:
  production: https://dashboard.heroku.com/apps/dreamtune

docs:
  getting_started: ./README.md
  app_specific: ./django-web-app/README.md

commands:
  bootstrap: script/bootstrap
  # No database data yet.
  database: https://console.firebase.google.com/u/0/project/dreamtune-cdf8a/database
  server: cd app/django-web-app; python3 manage.py runserver
  tests: echo "test command here" 
