name: ReactAppCI
on:
  push:
    branches:
      - firebase-migration
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    steps:
    - name: Install Packages
      working-directory: ./app
      run: npm install
    - name: Build the Website
      working-directory: ./app
      run: npm run build
    - name: Done!
      working-directory: ./app
      run: echo "The react app successfully builds!"
