name: ReactAppCI
on:
  push:
    branches:
      - firebase-migration
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      working-directory: ./app
      run: npm install
    - name: Build the Website
      working-directory: ./app
      run: npm run build
    - name: Done!
      working-directory: ./app
      run: echo "The react app successfully builds!"
    - name: "Upload to DCSIL App"
      env:
        DCSIL_TOKEN: ${{ secrets.DCSIL_TOKEN }}
      run: |
        # Send the command to the DCSIL App
        resp=$(curl -X POST -H "Content-Type: application/json" -H "Authorization: token $DCSIL_TOKEN" -H "X-App-Type: JavaScript" -d @coverage/coverage-summary.json https://dcsil-team-app.herokuapp.com/api/v1/repos/18/code_coverage)
        # Output the response from the DCSIL App
         echo $resp
         # Exit 1 if the response was an error, or if it did not meet requirements (currently a min 65.0%)
        exit $(echo $resp | jq 'if .success == false then 1 elif .meets_requirements == false then 1 else 0 end')
