name: ReactAppCI
on:
  push:
    branches:
      - firebase-migration
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Packages
      working-directory: ./app
      run: npm install
    - name: Build the Website
      working-directory: ./app
      run: npm run build
    - name: Done!
      working-directory: ./app
      run: echo "The react app successfully builds!"
